services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=hotel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root_senha_secreta
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    container_name: django_hotel
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_NAME=hotel
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
