# Generated by Django 6.0.2 on 2026-03-22 22:29
#
import django.db.models.deletion
from django.db import migrations, models
#

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('FAMILIA', 'Família')], default='SOLTEIRO', max_length=20)),
                ('status', models.CharField(choices=[('LIMPO', 'Limpo'), ('SUJO', 'Sujo'), ('MANUTENCAO', 'Manutenção'), ('OCUPADO', 'Ocupado')], default='LIMPO', max_length=20)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CHECK_IN', 'Check-in'), ('CHECK_OUT', 'Check-out'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hotel.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.quarto')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO_BANCARIO', 'Boleto Bancário')], max_length=30)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='hotel.reserva')),
            ],
        ),
    ]
