# Generated by Django 6.0.2 on 2026-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='id_transacao_externa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
