# Generated by Django 6.0.5 on 2026-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_consumacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO_BANCARIO', 'Boleto Bancário')], max_length=30, null=True),
        ),
    ]
