# Generated by Django 6.0.5 on 2026-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_pagamento_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('BOLETO_BANCARIO', 'Boleto Bancário'), ('DINHEIRO', 'Dinheiro')], max_length=30, null=True),
        ),
    ]
